In [20]:
import numpy as np
import cv2
import os
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

In [2]:
feature_dataset = np.load('bag_of_words_features.npy')

In [3]:
"""
Step 3:
Choose approximately half of the images from each category, as training data. Save the
rest as test data.
"""

'\nStep 3:\nChoose approximately half of the images from each category, as training data. Save the\nrest as test data.\n'

In [4]:
category_map = {'airplanes':1, 'Motorbikes':2,'Faces_easy':3}

In [5]:
#Splitting bow_data according to categories
category_bow_data = {}
for data in feature_dataset:
    if category_bow_data.has_key(data[1]):
        category_bow_data[data[1]].append(data[0])
    else:
        category_bow_data[data[1]]=[]    

In [6]:
#Splitting data into training and testing data
x_train,y_train,x_test,y_test = [[],[],[],[]]
category_count = {'airplanes':len(category_bow_data['airplanes']), 'Motorbikes':len(category_bow_data['Motorbikes']),
                  'Faces_easy':len(category_bow_data['Faces_easy'])}
for category in category_map:
    x_train.extend(category_bow_data[category][0:category_count[category]/2+1])
    y_train.extend([category_map[category] for _ in range(len(category_bow_data[category][0:category_count[category]/2+1]))])
    
    x_test.extend(category_bow_data[category][category_count[category]/2+1:])
    y_test.extend([category_map[category] for _ in range(len(category_bow_data[category][category_count[category]/2+1:]))])
    
x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)

In [16]:
"""
Step 4:
Train Normal Bayesian Classifier of OpenCV to distinguish between the three object
categories using the chosen training data.

Step 5:
Test the performance of the classifier separately with training data and the test data. Report
the accuracy and the confusion matrix .
"""

'\nStep 4:\nTrain Normal Bayesian Classifier of OpenCV to distinguish between the three object\ncategories using the chosen training data.\n\nStep 5:\nTest the performance of the classifier separately with training data and the test data. Report\nthe accuracy and the confusion matrix .\n'

In [18]:
#Normal Bayesian Classifier
#Training and Calculating Training and Testing Accuracy
normal_bayes_classifier = MultinomialNB()
normal_bayes_classifier.fit(x_train,y_train)
print normal_bayes_classifier.score(x_train,y_train),normal_bayes_classifier.score(x_test,y_test)

0.895771878073 0.880552813425


In [19]:
#Calculating the confusion matrix
y_pred = normal_bayes_classifier.predict(x_test)
print confusion_matrix(y_test,y_pred)

[[320  17  62]
 [  9 383   6]
 [  9  18 189]]


In [21]:
#Decision Tree
#Training and Calculating Training and Testing Accuracy
decision_tree_classifier = DecisionTreeClassifier()
decision_tree_classifier.fit(x_train,y_train)
print decision_tree_classifier.score(x_train,y_train),decision_tree_classifier.score(x_test,y_test)

1.0 0.780848963475


In [22]:
#Calculating the confusion matrix
y_pred = decision_tree_classifier.predict(x_test)
print confusion_matrix(y_test,y_pred)

[[321  35  43]
 [ 40 330  28]
 [ 49  27 140]]
